### ISSUE TITLE
ERROR_IMAGE_WRITE_FAILED = 9854;

### ISSUE THREAD

**Issue by alexadp1087** [kevalpatel2106/android-hidden-camera#24]
Hi, i have the error ERROR_IMAGE_WRITE_FAILED = 9854, i give the write external and internal permission on manifest but i don't understand why i received this error. 
Can you help me? 
Thank you

**Comment by kevalpatel2106** [comment]
@alexadp1087 Did you asked for the write external storage runtime permission before taking the picture?

**Comment by kevalpatel2106** [comment]
Closing the issue because of inactivity. If you face the same issue feel free to reopen this.

**Comment by dengue8830** [comment]
Hi! i have the same issue. In android 6 it works, but in android 4 throws an ERROR_IMAGE_WRITE_FAILED

```
03-07 16:54:31.011 8220-8369/com.taxip.app W/System.err: java.io.IOException: open failed: EINVAL (Invalid argument)
03-07 16:54:31.011 8220-8369/com.taxip.app W/System.err:     at java.io.File.createNewFile(File.java:950)
03-07 16:54:31.011 8220-8369/com.taxip.app W/System.err:     at com.androidhiddencamera.HiddenCameraUtils.saveImageFromFile(HiddenCameraUtils.java:138)
03-07 16:54:31.011 8220-8369/com.taxip.app W/System.err:     at com.androidhiddencamera.CameraPreview$1$1.run(CameraPreview.java:217)
03-07 16:54:31.011 8220-8369/com.taxip.app W/System.err:     at java.lang.Thread.run(Thread.java:841)
03-07 16:54:31.012 8220-8369/com.taxip.app W/System.err: Caused by: libcore.io.ErrnoException: open failed: EINVAL (Invalid argument)
03-07 16:54:31.012 8220-8369/com.taxip.app W/System.err:     at libcore.io.Posix.open(Native Method)
03-07 16:54:31.012 8220-8369/com.taxip.app W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
03-07 16:54:31.012 8220-8369/com.taxip.app W/System.err:     at java.io.File.createNewFile(File.java:943)
03-07 16:54:31.012 8220-8369/com.taxip.app W/System.err: 	... 3 more
```

**Comment by dengue8830** [comment]
i could reproduce the problem using the file path shown in the debug console
file name: `/storage/sdcard0/Android/data/com.taxip.app/cache:IMG_1520453738411.jpeg`
problem: `open failed: EINVAL (Invalid argument)`

the filename is invalid in that android's version
```
        File file = new File("/storage/sdcard0/Android/data/com.taxip.app/cache:IMG_1520453738411.jpeg");
        try {
            boolean resultado = file.createNewFile();
            Log.i("ok?", resultado + "");
        } catch (IOException e) {
            Log.e("error escribeindo", e);
        }
```

if i change the ':' for a '_' it works
