### ISSUE TITLE
Please solve this issue

### ISSUE THREAD

**Issue by Teja-developer** [kevalpatel2106/android-hidden-camera#26]
android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@3e47865 -- permission denied for window type 2006
                                                                   at android.view.ViewRootImpl.setView(ViewRootImpl.java:809)
                                                                   at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                                                                   at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                   at com.txusballesteros.bubbles.BubblesService$2.run(BubblesService.java:120)
                                                                   at android.os.Handler.handleCallback(Handler.java:789)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by kevalpatel2106** [comment]
@Teja-developer Can you please explain when this error occurs? Are you using it on the lock screen? What is your android version?
