### ISSUE TITLE
com.androidhiddencamera.CameraPreview not attached to window manager

### ISSUE THREAD

**Issue by pavlomelnyk** [kevalpatel2106/android-hidden-camera#42]
Hello
Help needed please.

java.lang.RuntimeException: Unable to stop service CaptureImageService@4dd86f3: java.lang.IllegalArgumentException: View=com.androidhiddencamera.CameraPreview{bdca1f1 V.E...... ......I. 0,0-1,1} not attached to window manager
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3657)
        at android.app.ActivityThread.-wrap26(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1722)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
     Caused by: java.lang.IllegalArgumentException: View=com.androidhiddencamera.CameraPreview{bdca1f1 V.E...... ......I. 0,0-1,1} not attached to window manager
        at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:497)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:406)
        at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:120)
        at com.androidhiddencamera.HiddenCameraService.stopCamera(HiddenCameraService.java:109)
        at com.androidhiddencamera.HiddenCameraService.onDestroy(HiddenCameraService.java:55)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3639)
        at android.app.ActivityThread.-wrap26(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1722) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6710)

Version 1.3.4
On LG g6 with android 8.0.0

**Comment by pavlomelnyk** [comment]
Hi. So I managed to workaround this issue by
`public class CaptureImageService extends HiddenCameraService {

    @Override

    public void onDestroy() {
           //super.onDestroy();
    }
...`

but it is not how it should be done:)
Waiting for your support. Thanks
