### ISSUE TITLE
 java.lang.RuntimeException: getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by pedrofsn** [kevalpatel2106/android-hidden-camera#44]
Moto G (2nd Gen) Android 6.0

```
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1974)
       at com.androidhiddencamera.CameraPreview.surfaceChanged(CameraPreview.java:102)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:593)
       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:606)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

and

XIAOMI Redmi 5 Android 7.1.2
```
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:2057)
       at com.androidhiddencamera.CameraPreview.surfaceChanged(CameraPreview.java:102)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:646)
       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:162)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2246)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1295)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6400)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
       at android.view.Choreographer.doCallbacks(Choreographer.java:688)
       at android.view.Choreographer.doFrame(Choreographer.java:623)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6228)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

**Comment by hamzaoubouzid** [comment]
Hi @pedrofsn please how did you resolve this prolem
