### ISSUE TITLE
App crashing when calling takePicture()

### ISSUE THREAD

**Issue by passiondroid** [kevalpatel2106/android-hidden-camera#6]
```java
FATAL EXCEPTION: main Process: , PID: 3794
java.lang.RuntimeException: Unable to start service tarun0.gyananter.CaptureService@7a5c685 with Intent { cmp=tarun0.gyananter/.CaptureService }: java.lang.RuntimeException: takePicture failed
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3335)
at android.app.ActivityThread.-wrap21(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

Caused by: java.lang.RuntimeException: takePicture failed
at android.hardware.Camera.native_takePicture(Native Method)
at android.hardware.Camera.takePicture(Camera.java:1461)
at android.hardware.Camera.takePicture(Camera.java:1406)
at com.androidhiddencamera.CameraPreview.takePictureInternal(CameraPreview.java:181)
at com.androidhiddencamera.HiddenCameraService.takePicture(HiddenCameraService.java:94)
at tarun0.gyananter.CaptureService.onStartCommand(CaptureService.java:63)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3318)
at android.app.ActivityThread.-wrap21(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6123) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
```

**Comment by kevalpatel2106** [comment]
@passiondroid Can you please tell me the steps to reproduce the bug?

**Comment by passiondroid** [comment]
@kevalpatel2106 It started coming today only. Earlier it was not crashing. I am using HiddenCameraService and when takePicture() is called within the service from onStartCommand(). It throws exception with logs  

> android.hardware.Camera.native_takePicture(Native Method)

**Comment by kevalpatel2106** [comment]
@passiondroid On which device you were testing?

**Comment by passiondroid** [comment]
@kevalpatel2106 Moto G4 plus

**Comment by kevalpatel2106** [comment]
Great! Let me check the problem. Meanwhile if you find the issue, you can always generate PR.

**Comment by passiondroid** [comment]
Ok, I will clone the repo from here as soon as i get some time. I dont know why it stopped working. It was working fine earlier.

**Comment by kevalpatel2106** [comment]
Are you using v1.3? or 1.2.1?

**Comment by passiondroid** [comment]
I am using 1.2.1

**Comment by kevalpatel2106** [comment]
Can you test if this issue still occues in v1.3? I made some changes in v1.3. (See commit : https://github.com/kevalpatel2106/android-hidden-camera/commit/73ce010210641ae5421c924983f2997fecea0723)

**Comment by passiondroid** [comment]
I am still getting the same exception after changing to 1.3

**Comment by kevalpatel2106** [comment]
@passiondroid I made some changes in latest version. Now, `HiddenCameraService` won't allow you to capture multiple photos simultaneously (like burst mode) because the camera is already acquired while capturing the second image.

Basically, `HiddenCameraService` won't allow you to take the second picture until the first picture is captured and processed.

**Comment by kevalpatel2106** [comment]
Fix in release v1.3.2.

**Comment by viks178** [comment]
**Maybe the question is still open**
`android.hardware.Camera.native_takePicture (Camera.java)
android.hardware.Camera.takePicture (Camera.java:1473)
android.hardware.Camera.takePicture (Camera.java:1418)
com.androidhiddencamera.CameraPreview.takePictureInternal (CameraPreview.java:196)
com.androidhiddencamera.HiddenCameraService.takePicture (HiddenCameraService.java:95)
com.app.mytest.MyCamService$1.run (MyCamService.java:77)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6776)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1518)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)`

On devices: 
Samsung SM-A320Y (API 24) Android 7.0
Samsung SM-G950F (API 24) Android 7.0
Samsung SM-J530FM (API 24) Android 7.0
Samsung SM-J710F (API 24) Android 7.0
Samsung SM-G930A (API 24) Android 7.0
Motorola Moto G Play (API 23) Android 6.0.1
Xiaomi Redmi Note 4 (Android API 24) Android 7.0

**Comment by thuan09878** [comment]
I'm using v1.3.3 and still facing this problem too. Any idea?

**Comment by Shouheng88** [comment]
can this https://stackoverflow.com/questions/21723557/java-lang-runtimeexception-takepicture-failed handle this problem ?

**Comment by sid96** [comment]
The problem has been in version 1.3.5...This version an be used to take images in burst mode..use that version instead.

**Comment by androidnoob123** [comment]
@sid96 can you please show how to take images in burst mode?

**Comment by gmolina75** [comment]
Add:
SurfaceTexture st = new SurfaceTexture(MODE_PRIVATE);
pCamera.setPreviewTexture(st);
before:
pCamera.startPreview();

works for me on honeywell ED70 , android 7
