### ISSUE TITLE
App crashing when initializing Activity

### ISSUE THREAD

**Issue by mubasoft** [kevalpatel2106/android-hidden-camera#8]
FATAL EXCEPTION: main
                                                                                               Process: com.example.mubashshir.screenlock_usesmartway, PID: 22058
                                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mubashshir.screenlock_usesmartway/com.example.mubashshir.screenlock_usesmartway.DemoCamActivity}: java.lang.RuntimeException: Root view of the activity/fragment cannot be frame layout
                                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2472)
                                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2534)
                                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:174)
                                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5550)
                                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
                                                                                                Caused by: java.lang.RuntimeException: Root view of the activity/fragment cannot be frame layout
                                                                                                   at com.androidhiddencamera.HiddenCameraActivity.addPreView(HiddenCameraActivity.java:132)
                                                                                                   at com.androidhiddencamera.HiddenCameraActivity.onCreate(HiddenCameraActivity.java:51)
                                                                                                   at com.example.mubashshir.screenlock_usesmartway.DemoCamActivity.onCreate(DemoCamActivity.java:27)
                                                                                                   at android.app.Activity.performCreate(Activity.java:6003)
                                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2425)
                                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2534) 
                                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:174) 
                                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424) 
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                                   at android.os.Looper.loop(Looper.java:194) 
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5550) 
                                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by mubasoft** [comment]
@kevalpatel2106  please have a look at this. I exactly imported your project. why i am getting this error?

**Comment by kevalpatel2106** [comment]
@mubasoft As the error suggest, the layout of your activity/fragment should not have `FrameLayout` as the root tag. It should be `RelativeLayout` or `LinearLayout`.

**Comment by mubasoft** [comment]
@kevalpatel2106  but i am not using frame layout anywhere in my project.

**Comment by mubasoft** [comment]
But i am not using frame layout anywhere then why i am getting this error?
